version: '2'

services:

  apigateway:
    build: ./ApiGateWay
    image: apigateway
    ports:
      - 8080:8080

  authservice:
    build: ./AuthService
    image: authservice
    ports:
      - 8090:8090

  client:
    build: ./Client/client
    image: client
    ports:
      - 3000:3000
      
