version: '2'

services:

  apigateway:
    build: ./ApiGateWay
    image: apigateway
    ports:
      - 8080:8080

  catalog:
    build: ./Catalog
    image: catalog
    ports:
      - 8095:8095

  
  authservice:
    build: ./AuthService
    image: authservice
    ports:
      - 8090:8090

  client:
    build: ./Client/client
    image: client
    ports:
      - 3000:3000

  rabbit:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
     - 5672:5672
     - 15672:15672
